version: '3.8'
services:
  test-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /app/Test-App
    volumes:
      - ../Test-App:/app/Test-App:delegated
    command: ["npx", "playwright", "test"]
    environment:
      - CI=true

  core-app-shell:
    build:
      context: ..
      dockerfile: modules-meta/core.app-shell/Dockerfile
    working_dir: /app/modules-meta/core.app-shell
    volumes:
      - ../modules-meta/core.app-shell:/app/modules-meta/core.app-shell:delegated
    command: ["npm", "run", "dev"]
    environment:
      - CI=true
    ports:
      - "5174:5174"
